### ISSUE TITLE
Extra approval when staking OMG tokens on l2

### ISSUE THREAD

**Issue by Ralph89** [omgnetwork/optimism#511] opened 2021-09-22 07:07 UTC
So steps to reproduce:

1: Approve the amount to stake on l2
2: Cancel the tx to stake (I did not cancel though, but I was doing something afk and went to screensaver, when I came back there was no tx available to stake, I needed to approve the amount I wanted to stake once more. resulting in 2 approve messages. 
I am quite sure if I cancelled the stake tx that popup after wards I would need to approve the amount once more

An idea is to check if the amount is approved, instead of asking to approve the amount everytime after declining / reloading a page.

**Comment by CAPtheorem** [comment] 2021-09-22 16:25
L1 staking for OMG will be fixed today. (The problem is the same as with the OMG bridging).

**Comment by CAPtheorem** [comment] 2021-09-22 17:49
Fixing in https://github.com/omgnetwork/optimism/pull/515 - will be live within a few hours.

**Closed by CAPtheorem** 2021-09-22 17:49 UTC
Labels: duplicate
