### ISSUE TITLE
Boba Gateway - Deposit Details Redirection Missing (Rinkeby)

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#383] opened 2021-09-09 15:56 UTC
When you deposit funds (traditional and fast deposit) from L1 > L2 you will get a window that the transaction is pending. The pending transaction has a 'details' button. When you press this button, it redirects you out of your wallet. 

![Bug Deposit Redirection Details](https://user-images.githubusercontent.com/90399189/132720372-ae119a84-97a7-4d65-8845-7d8f15bb7338.png)

**Comment by CAPtheorem** [comment] 2021-09-09 22:48
Humm yes that is not what was intended.

**Comment by osnysantos** [comment] 2021-09-10 09:45
This is not what is happening with me. I'm on `develop` but whenever I click `Details` button it just opens a new tab pointing to blockexplorer. Is not that expected? It's not redirecting me out of wallet though.

**Comment by Shaners42** [comment] 2021-09-10 10:28
Confirming that this issue is happening to me also. I get thrown back to initial Metamask page on clicking details.

**Comment by MitchellUnknown** [comment] 2021-09-10 10:32
> This is not what is happening with me. I'm on `develop` but whenever I click `Details` button it just opens a new tab pointing to blockexplorer. Is not that expected? It's not redirecting me out of wallet though.

I just cleared my cache, disabled every addblocker, but still got the wrong redirection. It opens a new tab though. That part works for me. But with the url: gateway.boba.network

**Comment by Shaners42** [comment] 2021-09-10 10:34
Just to note if you hover over the "details" link it points to https://gateway.boba.network/

**Comment by osnysantos** [comment] 2021-09-10 10:36
The issue is when disconnecting the wallet or the link the button points to? Or both? @MitchellUnknown 
The link it's pointing to here is: https://blockexplorer.rinkeby.boba.network/tx/0x81eb2c3c0117477f6cdea6c7cb31b100930c79bac3524b5abdb835b85c10df5b?network=Rinkeby so maybe the backend was changed,

**Comment by MitchellUnknown** [comment] 2021-09-10 10:37
> The issue is when disconnecting the wallet or the link the button points to? Or both? @MitchellUnknown
> The link it's pointing to here is: https://blockexplorer.rinkeby.boba.network/tx/0x81eb2c3c0117477f6cdea6c7cb31b100930c79bac3524b5abdb835b85c10df5b?network=Rinkeby so maybe the backend was changed,

![image](https://user-images.githubusercontent.com/90399189/132841163-c04ae5d4-02da-4032-89c8-4cb7cc781ff7.png)

**Comment by MitchellUnknown** [comment] 2021-09-10 12:21
The fast exit detail page is working correctly for example.

![image](https://user-images.githubusercontent.com/90399189/132852358-097c9bfe-2bcd-4c4b-9e98-e1629db15ef8.png)

![image](https://user-images.githubusercontent.com/90399189/132852479-37a857b4-1ebf-47b2-8639-39c28d2e2b5a.png)

**Comment by CAPtheorem** [comment] 2021-09-10 18:40
Yes the link that is being generated is bad. @osnysantos - the bug is in the ling generation code.

**Comment by sk-enya** [comment] 2021-09-12 08:27
yeah the chain was not detecting properly there it was like.
`L1pending` I added fix for this already

**Comment by CAPtheorem** [comment] 2021-09-12 18:58
Fixed - deploying - closed

**Closed by CAPtheorem** 2021-09-12 18:58 UTC
